# .github/workflows/build_release.yml

name: Build and Release Standalone Executable

on:
  push:
    branches:
      - main # Or your default branch, e.g., master

permissions:
  contents: write # Required to create releases and upload assets

jobs:
  build-windows-exe:
    runs-on: windows-latest # Use a Windows runner for .exe

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # Specify a Python version compatible with your dependencies

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable with PyInstaller
        run: |
          $MediaPipeRootPath = (Get-Command python).Module.ModuleBase | Split-Path | Join-Path -ChildPath "Lib\site-packages\mediapipe"
          $AddDataSource = Join-Path -Path $MediaPipeRootPath -ChildPath "modules\solution_base\*"
          $AddDataDest = "mediapipe\modules\solution_base" # Destination within the bundled app
          
          # Construct the value for --add-data as "SOURCE;DESTINATION"
          $FullAddDataValue = "{0};{1}" -f $AddDataSource, $AddDataDest
          
          Write-Output "MediaPipe Root Path: $MediaPipeRootPath"
          Write-Output "Calculated --add-data source: $AddDataSource"
          Write-Output "Calculated --add-data destination: $AddDataDest"
          Write-Output "Full value for --add-data: $FullAddDataValue"

          # Ensure the pyinstaller command arguments are clearly distinct.
          # The value for --add-data is quoted ("$FullAddDataValue") to handle potential spaces in paths.
          pyinstaller --name GestureFlow --onefile --noconsole --icon=NONE --add-data "$FullAddDataValue" main_app.py
        shell: pwsh

      - name: Get current date for release tag
        id: date
        run: echo "TAG_NAME=$(Get-Date -Format 'yyyyMMddHHmmss')" >> $env:GITHUB_OUTPUT
        shell: pwsh

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2 # A popular action for creating releases
        with:
          tag_name: ${{ steps.date.outputs.TAG_NAME }}
          name: Release ${{ steps.date.outputs.TAG_NAME }}
          body: |
            Automated release of GestureFlow.
            Executable built on commit ${{ github.sha }}.
          draft: false
          prerelease: false
          files: |
            dist/GestureFlow.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is automatically provided by GitHub
